#!/bin/sh

#-----------------------------
#COLORS
#-----------------------------
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White

# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White

# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red


#-----------------------------
#    SCRIPT
#-----------------------------

separator='\n---------------------------------------------\n'

echo $separator
echo $BCyan Create directories if not exists
echo $separator
echo app/cache
mkdir -p app/cache
echo app/logs
mkdir -p app/logs
echo data/uploads
mkdir -p data/uploads
echo web/media
mkdir -p web/media

echo $separator
echo $BCyan Composer install with optimizaion $Color_Off
echo $separator
composer install --verbose -o

echo $separator
echo $BCyan Setting ACLs $Color_Off
echo $separator
echo app/cache, app/logs, data, web/media
setfacl -R -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs data web/media
setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx app/cache app/logs data web/media
echo done.

echo $separator
echo $BCyan Updating database $Color_Off
echo $separator
php app/console doctrine:schema:validate
php app/console doctrine:schema:update --dump-sql

echo $separator
read -r -p "Voulez-vous mettre à jour la base de données ? [y/n]  " response
if [ "$response" = "y" ]; then
    echo Mise à jour de la base
    php app/console doctrine:schema:update --force
fi
echo $separator

echo $separator
echo $BCyan Clearing cache $Color_Off
echo $separator
php app/console cache:clear
php app/console cache:clear -e=prod

echo $separator
echo $BCyan Installing assets using Symlink $Color_Off
echo $separator
php app/console assets:install --symlink

echo $separator
read -r -p "Le projet utilise-il bower et node ? [y/n]  " response
if [ "$response" = "y" ]; then
    cd ./src/Ice/FrontendBundle/Resources

    echo $separator
    echo $BCyan NPM Install $Color_Off
    echo $separator

    npm install

    echo $separator
    echo $BCyan BOWER Install $Color_Off
    echo $separator

    bower install

    echo $separator
    echo $BCyan Grunt prod $Color_Off
    echo $separator

    grunt prod
fi

echo $separator
echo $BGreen Installation terminée ! $Color_Off
echo $separator